# 03_HT
---

![](img/ht.png)

In [22]:
# se limpia memoria
rm(list=ls())
gc()

       used    (Mb)  gc trigger (Mb)  limit (Mb) max used (Mb)
Ncells 2390701 127.7  4525722   241.7    NA       4525722 241.7
Vcells 4258552  32.5 10146329    77.5 16384      10146327  77.5

In [23]:
library(yaml)
require("data.table")
require("primes")
require("lightgbm") #Optimización bayesiana
require("DiceKriging")
require("mlrMBO")
require("rlist")

In [24]:
setwd("/Users/ppando/Materias/cs-datos/especializacion/ciencia-datos/exp/")

In [25]:
PARAMS <- read_yaml("03_HT_prxs_01a.yml")

In [26]:
# se graba a un archivo los componentes de lista
# para el primer registro, escribe antes los titulos

loguear  <- function(reg, arch=NA, folder="./exp/", ext=".txt", verbose=TRUE) {
  archivo  <- arch
  if (is.na(arch))
      archivo  <- paste0(folder, substitute(reg), ext)
  
  if (!file.exists(archivo)) {
    linea  <- paste0("fecha\t", paste(list.names(reg), collapse="\t" ), "\n")
    cat(linea, file = archivo)
  }
  
  linea  <- paste0(format(Sys.time(), "%Y%m%d %H%M%S"),  "\t", gsub( ", ", "\t", toString(reg)),  "\n")
  cat(linea, file = archivo, append = TRUE)
  if(verbose)
      cat(linea)   # se imprime por pantalla
}

In [27]:
parametrizar  <- function(lparam) {
  param_fijos  <- copy(lparam)
  hs  <- list()

  for (param in names(lparam)) {

    if (length(lparam[[param]]) > 1) {
      desde  <- as.numeric(lparam[[param]][[1]])
      hasta  <- as.numeric(lparam[[param]][[2]])

      if (length(lparam[[param]]) == 2) {
         hs  <- append(hs, list(makeNumericParam(param, lower= desde, upper= hasta)))
      } else {
         hs  <- append(hs, list(makeIntegerParam(param, lower= desde, upper= hasta)))
      }

      param_fijos[[param]] <- NULL  
    }
  }

  return(list("param_fijos" = param_fijos, "paramSet" = hs))
}

In [28]:
# particionar un dataset en forma estratificada
particionar  <- function(data,  division, agrupa="",  campo="fold", start=1, seed=NA) {
  if (!is.na(seed))
      set.seed(seed)

  bloque  <- unlist(mapply(function(x,y) {rep(y, x)}, division, seq(from=start, length.out=length(division))))  

  data[ , (campo) :=  sample(rep(bloque, ceiling(.N/length(bloque))))[1:.N], by= agrupa]
}

In [29]:
EstimarGanancia_lightgbm  <- function(x) {
  gc()
  GLOBAL_iteracion  <<- GLOBAL_iteracion + 1

  param_completo  <- c(param_fijos, x)

  param_completo$num_iterations         <- ifelse(param_fijos$boosting== "dart", 999, 99999)  #un numero muy grande
  param_completo$early_stopping_rounds  <- as.integer(200 + 4/param_completo$learning_rate)

  # vprob_optima  <<- c()
  set.seed(param_completo$seed)
  modelo_train  <- lgb.train( data= dtrain,
                              valids= list(valid = dvalidate),
                              param=  param_completo,
                              verbose= -100 )


  #aplico el modelo a testing y calculo la ganancia
  prediccion  <- predict( modelo_train, 
                          data.matrix( dataset_test[ , campos_buenos, with=FALSE]))

  tbl  <- dataset_test[ , c(PARAMS$param$const$campo_clase),with=F]
  tbl[ , pred := prediccion]

  gc()

  ganancia_test_normalizada  <- unlist(modelo_train$record_evals$valid[[PARAMS$param$lightgbm$metric]]$eval)[ modelo_train$best_iter ]
  
  rm(tbl)
  gc()
  
  #voy grabando las mejores column importance
  if (ganancia_test_normalizada <  GLOBAL_ganancia) {
    GLOBAL_ganancia  <<- ganancia_test_normalizada
    tb_importancia    <- as.data.table(lgb.importance(modelo_train))

    fwrite( tb_importancia,
            file= paste0(PARAMS$param$files$output$importancia, GLOBAL_iteracion, ".txt"),
            sep= "\t" )
  }

  #logueo final
  ds  <- list("cols"= ncol(dtrain),  "rows"= nrow(dtrain))
  xx  <- c(ds, copy(param_completo))

  xx$early_stopping_rounds  <- NULL
  xx$num_iterations  <- modelo_train$best_iter
  xx$ganancia  <- ganancia_test_normalizada
  xx$iteracion_bayesiana  <- GLOBAL_iteracion

  loguear(xx, arch = PARAMS$param$files$output$BOlog)

  return (ganancia_test_normalizada)
}

## Main

In [ ]:
set.seed(PARAMS$param$semilla) 

#se carga el dataset que tiene la Training Strategy
nom_arch <- PARAMS$param$files$input$dentrada 
dataset  <- fread(nom_arch)

# los campos que se pueden utilizar para la prediccion
campos_buenos <- setdiff(copy(colnames(dataset)), c(PARAMS$param$const$campo_clase, "part_train","part_validate","part_test"))

# la particion de train siempre va
dtrain  <- lgb.Dataset(data =  data.matrix(dataset[part_train==1, campos_buenos, with=FALSE]),
                       label = dataset[part_train==1][[PARAMS$param$const$campo_clase]],
                       free_raw_data = FALSE)


# se calcula validation y testing, segun corresponda
if (PARAMS$param$crossvalidation == FALSE) {
  if (PARAMS$param$validate == TRUE) {
    dvalidate  <- lgb.Dataset(data =  data.matrix(dataset[part_validate==1, campos_buenos, with=FALSE]),
                              label = dataset[part_validate==1][[PARAMS$param$const$campo_clase]],
                              free_raw_data = FALSE)

    dataset_test  <- dataset[part_test== 1]
    test_multiplicador  <- 1
  } else {
    # se divide en mitades los datos de testing
    particionar( dataset, 
                 division= c(1,1),
                 agrupa= c("part_test", PARAMS$param$const$campo_periodo), 
                 seed= PARAMS$param$semilla,
                 campo= "fold_test"
                )

    # fold_test==1  lo tomo para validation
    dvalidate  <- lgb.Dataset( data=  data.matrix(dataset[ part_test==1 & fold_test==1, campos_buenos, with=FALSE]),
                               label= dataset[part_test==1 & fold_test==1, PARAMS$param$const$campo_clase],
                               free_raw_data= FALSE
                             )

    dataset_test  <- dataset[part_test==1 & fold_test==2, ]
    test_multiplicador  <- 2
  }

}


rm(dataset)
gc()


# se prepara todo para la Bayesian Optimization -------------------------------------
hiperparametros <- PARAMS$param[[PARAMS$param$algoritmo]]
apertura  <- parametrizar(hiperparametros)
param_fijos  <-  apertura$param_fijos


#si ya existe el archivo log, traigo hasta donde procese
if (file.exists(PARAMS$param$files$output$BOlog)) {
  tabla_log  <- fread(PARAMS$param$files$output$BOlog)
  GLOBAL_iteracion  <- nrow(tabla_log)
  GLOBAL_ganancia   <- tabla_log[ , min(ganancia)]
  rm(tabla_log)
} else  {
  GLOBAL_iteracion  <- 0
  GLOBAL_ganancia   <- Inf
}

# aqui comienza la configuracion de mlrMBO
if (PARAMS$param$crossvalidation) {
  funcion_optimizar  <- EstimarGanancia_lightgbmCV
} else {
  funcion_optimizar  <- EstimarGanancia_lightgbm
}

configureMlr(show.learner.output= FALSE)

# se configura la busqueda bayesiana, los hiperparametros que se van a optimizar
obj.fun  <- makeSingleObjectiveFunction(
              fn =      funcion_optimizar, #la funcion que voy a maximizar
              minimize= PARAMS$param$BO$minimize,   #estoy Maximizando la ganancia
              noisy=    PARAMS$param$BO$noisy,
              par.set=  makeParamSet( params= apertura$paramSet ),     #definido al comienzo del programa
              has.simple.signature = PARAMS$param$BO$has.simple.signature   #paso los parametros en una lista
             )

#archivo donde se graba y cada cuantos segundos
ctrl  <- makeMBOControl(save.on.disk.at.time= PARAMS$param$BO$save.on.disk.at.time, save.file.path= PARAMS$param$files$output$BObin )  
                         
ctrl  <- setMBOControlTermination(ctrl, iters= PARAMS$param$BO$iterations)   #cantidad de iteraciones
                                   
ctrl  <- setMBOControlInfill(ctrl, crit= makeMBOInfillCritEI())

#establezco la funcion que busca el maximo
surr.km  <- makeLearner("regr.km",
                        predict.type= "se",
                        covtype= "matern3_2",
                        control= list(trace= TRUE))

# aqui se inicia la optimizacion bayesiana
if (!file.exists(PARAMS$param$files$output$BObin)) {
    run  <- mbo(obj.fun, learner= surr.km, control= ctrl)
} else {
    # si ya existe el archivo RDATA, se debe continuar desde el punto hasta donde llegue
    # usado para cuando se corta la virtual machine
    run  <- mboContinue( PARAMS$param$files$output$BObin)   # se retoma en caso que ya exista
}

       used    (Mb)  gc trigger (Mb)  limit (Mb) max used (Mb)
Ncells 2491083 133.1  4525722   241.7    NA       4525722 241.7
Vcells 8090994  61.8 21308951   162.6 16384      18972579 144.8

Computing y column(s) for design. Not provided.

20251123 172620	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0684417041653069	0.667025725623535	3777	54796	1	2.16784376388978	1
20251123 172622	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.191535269288579	0.554696707922267	13378	63812	1	2.16784376388978	2
20251123 172643	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0851192367571639	0.375601522153011	12222	46501	1763	2.13675665289513	3
20251123 172719	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.258500224731397	0.547033663497132	18705	26423	2880	1.84290797442822	4
20251123 172832	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.105658529841457	0.820036890696792	6010	40616	15591	2.06129061767349	5
20251123 172835	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.116614184862701	0.173240938984964	187	49064	1	2.16784376388978	6
20251123 172854	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.169999149683863	0.478721408244746	9871	11807	1373	1.80666506338351	7
20251123 172938	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.139707736934652	0.245789536644588	17449	36030	4772	1.95510722768411	8
20251123 173306	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0223084168997593	0.720434085135639	10405	28451	29349	1.85559732346399	9
20251123 173309	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.23300667146279	0.913690242878511	7467	72885	1	2.16784376388978	10
20251123 173311	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.21476217489806	0.275572550525249	8260	58094	1	2.16784376388978	11
20251123 173321	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.211677008928382	0.982975072004774	16167	2575	442	1.84188778190547	12
20251123 173327	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.270630956009263	0.861698278502445	2183	18685	948	1.85020537849827	13
20251123 173348	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.29210329632333	0.109330803800549	14818	7113	1904	1.81488469774627	14
20251123 173350	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.147327613467933	0.618828268720245	19031	67979	1	2.16784376388978	15
20251123 173417	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0522792100254446	0.404187323396036	3171	23303	2894	1.85339656903448	16

[mbo] 0: learning_rate=0.0684; feature_fraction=0.667; num_leaves=3777; min_data_in_leaf=54796 : y = 2.17 : 1.1 secs : initdesign

[mbo] 0: learning_rate=0.192; feature_fraction=0.555; num_leaves=13378; min_data_in_leaf=63812 : y = 2.17 : 2.4 secs : initdesign

[mbo] 0: learning_rate=0.0851; feature_fraction=0.376; num_leaves=12222; min_data_in_leaf=46501 : y = 2.14 : 20.2 secs : initdesign

[mbo] 0: learning_rate=0.259; feature_fraction=0.547; num_leaves=18705; min_data_in_leaf=26423 : y = 1.84 : 36.3 secs : initdesign

[mbo] 0: learning_rate=0.106; feature_fraction=0.82; num_leaves=6010; min_data_in_leaf=40616 : y = 2.06 : 73.4 secs : initdesign

[mbo] 0: learning_rate=0.117; feature_fraction=0.173; num_leaves=187; min_data_in_leaf=49064 : y = 2.17 : 2.5 secs : initdesign

[mbo] 0: learning_rate=0.17; feature_fraction=0.479; num_leaves=9871; min_data_in_leaf=11807 : y = 1.81 : 18.7 secs : initdesign

[mbo] 0: learning_rate=0.14; feature_fraction=0.246; num_leaves=17449; min_data_in_leaf=36030 : y = 1.96 : 44.7 secs : initdesign

[mbo] 0: learning_rate=0.0223; feature_fraction=0.72; num_leaves=10405; min_data_in_leaf=28451 : y = 1.86 : 207.4 secs : initdesign

[mbo] 0: learning_rate=0.233; feature_fraction=0.914; num_leaves=7467; min_data_in_leaf=72885 : y = 2.17 : 3.2 secs : initdesign

[mbo] 0: learning_rate=0.215; feature_fraction=0.276; num_leaves=8260; min_data_in_leaf=58094 : y = 2.17 : 1.8 secs : initdesign

[mbo] 0: learning_rate=0.212; feature_fraction=0.983; num_leaves=16167; min_data_in_leaf=2575 : y = 1.84 : 9.9 secs : initdesign

[mbo] 0: learning_rate=0.271; feature_fraction=0.862; num_leaves=2183; min_data_in_leaf=18685 : y = 1.85 : 6.0 secs : initdesign

[mbo] 0: learning_rate=0.292; feature_fraction=0.109; num_leaves=14818; min_data_in_leaf=7113 : y = 1.81 : 21.2 secs : initdesign

[mbo] 0: learning_rate=0.147; feature_fraction=0.619; num_leaves=19031; min_data_in_leaf=67979 : y = 2.17 : 2.0 secs : initdesign

[mbo] 0: learning_rate=0.0523; feature_fraction=0.404; num_leaves=3171; min_data_in_leaf=23303 : y = 1.85 : 26.9 secs : initdesign

20251123 173614	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0329569284702933	0.604969568810164	19996	16082	9816	1.83769260940135	17

[mbo] 1: learning_rate=0.033; feature_fraction=0.605; num_leaves=19996; min_data_in_leaf=16082 : y = 1.84 : 116.3 secs : infill_ei

20251123 173634	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.298360688901701	0.523019613754303	13943	11089	1283	1.79578218414557	18

[mbo] 2: learning_rate=0.298; feature_fraction=0.523; num_leaves=13943; min_data_in_leaf=11089 : y = 1.8 : 20.1 secs : infill_ei

Saved the current state after iteration 3 in the file BO_bin.RDATA.

20251123 173647	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.274734296629428	0.293764252321945	14082	14332	957	1.8461329106139	19

[mbo] 3: learning_rate=0.275; feature_fraction=0.294; num_leaves=14082; min_data_in_leaf=14332 : y = 1.85 : 12.1 secs : infill_ei

20251123 173654	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.29997112991831	0.629556324501507	10140	7959	537	1.83093993145995	20

[mbo] 4: learning_rate=0.3; feature_fraction=0.63; num_leaves=10140; min_data_in_leaf=7959 : y = 1.83 : 7.4 secs : infill_ei

20251123 173717	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.190912943156016	0.57045759119652	19984	10395	1540	1.80560287134336	21

[mbo] 5: learning_rate=0.191; feature_fraction=0.57; num_leaves=19984; min_data_in_leaf=10395 : y = 1.81 : 22.5 secs : infill_ei

20251123 173803	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0713445971782184	0.99869428401609	14181	11359	4810	1.80181649775953	22

[mbo] 6: learning_rate=0.0713; feature_fraction=0.999; num_leaves=14181; min_data_in_leaf=11359 : y = 1.8 : 45.2 secs : infill_ei

20251123 174157	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0201093843472983	0.485141685841784	14404	10627	15864	1.79999980290766	23

[mbo] 7: learning_rate=0.0201; feature_fraction=0.485; num_leaves=14404; min_data_in_leaf=10627 : y = 1.8 : 234.7 secs : infill_ei

20251123 174303	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0618222273185743	0.100634673071049	16134	7	69	1.76939511963573	24

[mbo] 8: learning_rate=0.0618; feature_fraction=0.101; num_leaves=16134; min_data_in_leaf=7 : y = 1.77 : 65.7 secs : infill_ei

20251123 174423	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.020980505849692	0.102032697804679	1235	7	499	1.74585528574372	25

[mbo] 9: learning_rate=0.021; feature_fraction=0.102; num_leaves=1235; min_data_in_leaf=7 : y = 1.75 : 79.3 secs : infill_ei

20251123 174431	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.107485707351464	0.104728564399972	13	30	788	1.75086412340669	26

[mbo] 10: learning_rate=0.107; feature_fraction=0.105; num_leaves=13; min_data_in_leaf=30 : y = 1.75 : 7.6 secs : infill_ei

20251123 174518	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0291075076172063	0.100212290191283	12	1976	5237	1.79729700395308	27

[mbo] 11: learning_rate=0.0291; feature_fraction=0.1; num_leaves=12; min_data_in_leaf=1976 : y = 1.8 : 47.1 secs : infill_ei

20251123 174753	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0278656177980542	0.432557320117834	3564	0	92	1.6950787740079	28

[mbo] 12: learning_rate=0.0279; feature_fraction=0.433; num_leaves=3564; min_data_in_leaf=0 : y = 1.7 : 154.1 secs : infill_ei

Saved the current state after iteration 13 in the file BO_bin.RDATA.

20251123 174834	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0201771853512001	0.62019544882358	1615	0	141	1.74931901377467	29

[mbo] 13: learning_rate=0.0202; feature_fraction=0.62; num_leaves=1615; min_data_in_leaf=0 : y = 1.75 : 40.6 secs : infill_ei

20251123 174952	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.127407087544226	0.391488292309825	8906	2	20	1.72823244123196	30

[mbo] 14: learning_rate=0.127; feature_fraction=0.391; num_leaves=8906; min_data_in_leaf=2 : y = 1.73 : 78.4 secs : infill_ei

20251123 175007	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.288205058052839	0.323828613886595	2739	11	6	1.84305101893655	31

[mbo] 15: learning_rate=0.288; feature_fraction=0.324; num_leaves=2739; min_data_in_leaf=11 : y = 1.84 : 14.9 secs : infill_ei

20251123 181043	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0204380106006837	0.413369508395084	7804	1	141	1.69289928506581	32

[mbo] 16: learning_rate=0.0204; feature_fraction=0.413; num_leaves=7804; min_data_in_leaf=1 : y = 1.69 : 1235.0 secs : infill_ei

Saved the current state after iteration 17 in the file BO_bin.RDATA.

20251123 181247	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0204534486162776	0.380924583418336	5802	1	132	1.70204544775448	33

[mbo] 17: learning_rate=0.0205; feature_fraction=0.381; num_leaves=5802; min_data_in_leaf=1 : y = 1.7 : 124.2 secs : infill_ei

20251123 181445	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0339792948570986	0.457855214102674	8047	7	77	1.73038131392711	34

[mbo] 18: learning_rate=0.034; feature_fraction=0.458; num_leaves=8047; min_data_in_leaf=7 : y = 1.73 : 117.3 secs : infill_ei

20251123 181459	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0203372030532376	0.873093088553894	43	6	1083	1.7753876610339	35

[mbo] 19: learning_rate=0.0203; feature_fraction=0.873; num_leaves=43; min_data_in_leaf=6 : y = 1.78 : 14.1 secs : infill_ei

20251123 181656	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0204953025996849	0.760674200381835	85	9536	12921	1.80803186566113	36

[mbo] 20: learning_rate=0.0205; feature_fraction=0.761; num_leaves=85; min_data_in_leaf=9536 : y = 1.81 : 116.1 secs : infill_ei

20251123 181807	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0270325074425562	0.999378498087191	19949	24911	7461	1.85799649571222	37

[mbo] 21: learning_rate=0.027; feature_fraction=0.999; num_leaves=19949; min_data_in_leaf=24911 : y = 1.86 : 71.3 secs : infill_ei

20251123 182540	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0218429210333403	0.777302880429048	19994	7	127	1.78553484547866	38

[mbo] 22: learning_rate=0.0218; feature_fraction=0.777; num_leaves=19994; min_data_in_leaf=7 : y = 1.79 : 452.6 secs : infill_ei

Saved the current state after iteration 23 in the file BO_bin.RDATA.

20251123 182626	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0202448458822045	0.219425897732304	3100	1	164	1.71494349430595	39

[mbo] 23: learning_rate=0.0202; feature_fraction=0.219; num_leaves=3100; min_data_in_leaf=1 : y = 1.71 : 45.3 secs : infill_ei

20251123 182820	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0225740582759698	0.39258146038206	2515	35	876	1.73812846844683	40

[mbo] 24: learning_rate=0.0226; feature_fraction=0.393; num_leaves=2515; min_data_in_leaf=35 : y = 1.74 : 113.4 secs : infill_ei

20251123 182830	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.137060426101027	0.101081674471202	5314	16	52	1.77180875924964	41

[mbo] 25: learning_rate=0.137; feature_fraction=0.101; num_leaves=5314; min_data_in_leaf=16 : y = 1.77 : 10.0 secs : infill_ei

20251123 183246	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.020170300444948	0.960072524325362	4154	135	2692	1.79449452410039	42

[mbo] 26: learning_rate=0.0202; feature_fraction=0.96; num_leaves=4154; min_data_in_leaf=135 : y = 1.79 : 255.3 secs : infill_ei

20251123 183314	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0202387177398282	0.100208888480776	7398	43	530	1.74685314994693	43

[mbo] 27: learning_rate=0.0202; feature_fraction=0.1; num_leaves=7398; min_data_in_leaf=43 : y = 1.75 : 27.8 secs : infill_ei

20251123 202021	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0204547832165542	0.337583414180398	19051	2	112	1.71749606525146	44

[mbo] 28: learning_rate=0.0205; feature_fraction=0.338; num_leaves=19051; min_data_in_leaf=2 : y = 1.72 : 6426.5 secs : infill_ei

Saved the current state after iteration 29 in the file BO_bin.RDATA.

20251123 202310	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0202889770170742	0.174229623820416	10160	1	144	1.72306754274981	45

[mbo] 29: learning_rate=0.0203; feature_fraction=0.174; num_leaves=10160; min_data_in_leaf=1 : y = 1.72 : 169.1 secs : infill_ei

20251123 202545	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0201371291926223	0.884278859032342	19932	10153	12675	1.80214182670879	46

[mbo] 30: learning_rate=0.0201; feature_fraction=0.884; num_leaves=19932; min_data_in_leaf=10153 : y = 1.8 : 154.4 secs : infill_ei

20251123 202655	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0608946347217634	0.272149207899352	10299	6	61	1.73851191945979	47

[mbo] 31: learning_rate=0.0609; feature_fraction=0.272; num_leaves=10299; min_data_in_leaf=6 : y = 1.74 : 69.4 secs : infill_ei

20251123 202816	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0420067961910569	0.427033857392233	6212	0	54	1.69966884391617	48

[mbo] 32: learning_rate=0.042; feature_fraction=0.427; num_leaves=6212; min_data_in_leaf=0 : y = 1.7 : 80.8 secs : infill_ei

20251123 202837	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0203308843558469	0.540504376098273	154	4	736	1.76501670023862	49

[mbo] 33: learning_rate=0.0203; feature_fraction=0.541; num_leaves=154; min_data_in_leaf=4 : y = 1.77 : 20.5 secs : infill_ei

20251123 202908	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.282498995876269	0.422686397936767	19940	53	57	1.82166088926194	50

[mbo] 34: learning_rate=0.282; feature_fraction=0.423; num_leaves=19940; min_data_in_leaf=53 : y = 1.82 : 31.2 secs : infill_ei

20251123 203133	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0202822273140294	0.367297068661361	11491	37	1029	1.75384966311609	51

[mbo] 35: learning_rate=0.0203; feature_fraction=0.367; num_leaves=11491; min_data_in_leaf=37 : y = 1.75 : 144.7 secs : infill_ei

Saved the current state after iteration 36 in the file BO_bin.RDATA.

20251123 203232	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0209323498585105	0.193320438140134	19981	80	660	1.74738903436051	52

[mbo] 36: learning_rate=0.0209; feature_fraction=0.193; num_leaves=19981; min_data_in_leaf=80 : y = 1.75 : 58.2 secs : infill_ei

20251123 203507	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0202370369881255	0.370598800156247	7082	50	1506	1.7455710127297	53

[mbo] 37: learning_rate=0.0202; feature_fraction=0.371; num_leaves=7082; min_data_in_leaf=50 : y = 1.75 : 154.4 secs : infill_ei

20251123 204035	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0200886714382822	0.843362074965486	10960	0	87	1.84148024749431	54

[mbo] 38: learning_rate=0.0201; feature_fraction=0.843; num_leaves=10960; min_data_in_leaf=0 : y = 1.84 : 328.0 secs : infill_ei

20251123 204054	32	98054	0	0	0	1	1	1	-1	1023	999983	FALSE	0.1	50	0.5	rmse	TRUE	regression	TRUE	TRUE	FALSE	gbdt	0	-100	-100	0.0302579649463154	0.136510104026465	3420	13	172	1.76705952192567	55

[mbo] 39: learning_rate=0.0303; feature_fraction=0.137; num_leaves=3420; min_data_in_leaf=13 : y = 1.77 : 19.0 secs : infill_ei